[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { version = "0.1.0", path = "../domain" }
shared = { version = "0.1.0", path = "../shared" }
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio-rustls", "macros"] }
