[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
uuid = { version = "1.16.0", features = ["v4"] }
axum = { workspace = true }
domain = { path = "../domain" }
